try: 
    print(x)
except NameError as e:
    print ('Excetion raised:' , e)
	
	